# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8b9be936b2c590fe4ec9078735002e6476701a28261b32c4cda0126e89a70d45bd1d56721a4cbd34a148bc9dc4955aa4731fe69254d3d2c95d68fbcc8bd9ca

test:
  secret_key_base: b6772490371c79e7a0b0712ce65c8bebec4e8182a40d814a4d47c0d9805901171011881370922c99e4b8c9abdee8d581782e945407c2c9eb5847a3f2b90d354f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
